version: 2
updates:
- package-ecosystem: nuget
  directories:
    - "/src/EFCoreViewer"
    - "/src/IQueryableObjectSource"
  schedule:
    interval: daily
  assignees:
    - "sboulema"

- package-ecosystem: github-actions
  directory: "/"
  schedule:
    interval: weekly
  assignees:
    - "sboulema"